
debug: true

log_dir_file_name: "./dmail-mint-agent"

icp_config:
  identity_pem_path: "./dmail-identity.pem" # which is pem of controller.

  # pro
  icp_domain: "https://42fn2-wyaaa-aaaak-aafwq-cai.raw.ic0.app/"
  agent_canister_id: "42fn2-wyaaa-aaaak-aafwq-cai"

  # dev 
  # icp_domain: "http://localhost:8000/"
  # agent_canister_id: "r7inp-6aaaa-aaaaa-aaabq-cai"

database_url: "mysql://root:123456@localhost:3306/dmail_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8"


  


