
debug: true

log_dir_file_name: "./dmail-mint-agent"

icp_config:
  identity_pem_path: "./dmail-identity.pem" # which is pem of controller.

  # pro
  # icp_domain: "https://5xlju-zqaaa-aaaak-aafra-cai.raw.ic0.app/"
  # agent_canister_id: "5xlju-zqaaa-aaaak-aafra-cai"

  # dev 
  icp_domain: "http://localhost:8000/"
  agent_canister_id: "ryjl3-tyaaa-aaaaa-aaaba-cai"

database_url: "mysql://root:123456@localhost:3306/dmail_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8"


  


